### ISSUE TITLE
Open installer error on LOLIN S2 Mini

### ISSUE THREAD

**Issue by tytoalba99** [adafruit/web-firmware-installer-js#5]
### CircuitPython version

```python
CircuitPython 8.0.4
```

### Code/REPL

```python
Not applicable
```

### Behavior

When installing CircuitPython 8.0.4 on a LOLIN S2 Mini board the installer does not adavance.

### Description

Debugging the code in the browser terminal the bin file URL with the firmware has a double slash "//" so a 404 error is return and never goes on.

### Additional information

https://circuitpython.org/board/lolin_s2_mini/

**Comment by makermelissa** [comment]
This was fixed by https://github.com/adafruit/circuitpython-org/pull/1172.
