### ISSUE TITLE
Windows doesn't return boot drive label, so UF2 install always fails in web-installer

### ISSUE THREAD

**Issue by tyeth** [adafruit/web-firmware-installer-js#9]
Selecting the correctly named drive in windows doesn't work, as the browser gets an unrelated drive label of \ [It's actually QTPYS2BOOT right now]
![image](https://github.com/adafruit/circuitpython-org/assets/6692083/e466281d-5a08-4f76-8b4f-ae8a3087de11)

A nice solution might be to ask the user to abort, retry and select the drive again, or ignore (and continue to copy uf2 / work with this device). Maybe abort/retry/ignore is too clunky, but you get the idea, some cancel/continue dialog.

Another similar issue is when the code.circuitpython.org cannot recognise a drive because it has the wrong label (due to user renaming), or a device sharing same partition layout when using uf2 e.g. having a circuitpython device labelled WIPPER

On a related note the code.py doesn't get created but the boot_out.txt does if using a previously compatible partition size - confused the heck out of me until i deleted both wipper_bootlog.txt and boot_out.txt and the later was recreated on reset [still no code.py as partition was compatible]). Presumably that's a known one or should I file an issue for that in circuitpython repo?

**Comment by makermelissa** [comment]
Transferring to correct repo as this is where the change needs to happen.
